#' Add Value
#'
#' The ADDVALUE function adds a value to a GTS, without checking for tick duplicates.
#' The added data point is appended to the GTS. The SETVALUE overrides an existing value.
#'
#' The ADDVALUE function only works on GTS, not on lists of GTS like those generated by the use of FETCH.
#' If you want to use ADDVALUE after a FETCH, you will need to extract the GTS from the list,
#' for example by using GET with value 0 as parameter.
#'
#' If latitude or longitude are NaN (not a number), value has only timestamp, elevation, value.
#' If elevation is NaN (not a number), value has only timestamp, latitude, longitude, value.
#' If elevation is NaN and longitude or latitude are NaN, value has only timestamp, value.
#'
#' When adding a Geo Time Series™ or GTS Encoder value,
#' the value will be wrapped (as when using WRAPRAW) and added as a binary value.
#'
#' @inheritParams documentation
#'
#' @param tick Timestamp
#' @param value Value of the tick.
#' @param latitude,longitude Coordinates.
#' @param elevation Elevation.
#'
#' @examples
#' \dontrun{
#'   con <- wrp_connect()
#'   con %>%
#'     clear_script() %>%
#'     wrp_new_gts() %>%
#'     wrp_rename("test") %>%
#'     wrp_add_value(tick = 100, value = TRUE) %>%
#'     wrp_add_value(tick = 110, longitude = 45, value = TRUE) %>%
#'     wrp_add_value(tick = 120, latitude = 1.2, elevation = 250, value = TRUE) %>%
#'     wrp_add_value(tick = 130, latitude = 48.44218, longitude = -4.41427,
#'                   elevation = 80000, value = TRUE) %>%
#'     wrp_add_value(tick = 100, value = FALSE) %>%
#'     wrp_exec()
#' }
#'
#' @export
#'
wrp_add_value <- function(wrp_con, tick, value, latitude = NA, longitude = NA, elevation = NA) {
  if (is.logical(value))        value <- as.character(tolower(value))
  else if (is.character(value)) value <- sanitize(value)

  if (lubridate::is.Date(tick))    tick <- as.numeric(lubridate::as_datetime(tick)) * 1e6
  if (lubridate::is.POSIXct(tick)) tick <- as.numeric(tick) * 1e6
  script <- glue::glue("{tick} {latitude} {longitude} {elevation} {value} ADDVALUE", .na = "NaN")
  wrp_con$set_script(script)
  wrp_con$add_stack("gts", "gts")
  return(wrp_con)
}

#' Add Value from DataFrame
#'
#' Add values to a GTS from a data.frame.
#'
#' @seealso wrp_add_value
#'
#' @inheritParams documentation
#' @param df A dataframe
#' @param tick column representing Timestamp, could be numeric or date values
#' @param value column representing value
#' @param latitude,longitude columns representing coordinates. Can be NULL.
#' @param elevation column representing elevation. Can be NULL.
#'
#' @examples
#' \dontrun{
#'   library(tibble)
#'   df <- tribble(
#'     ~ tick, ~ value, ~ latitude, ~ longitude, ~ elevation,
#'     100   , TRUE   , NA        , NA         , NA,
#'     110   , TRUE   , 45        , NA         , NA,
#'     120   , TRUE   , NA        , 1.2        , 250,
#'     130   , TRUE   , 48.44218  , -4.41427   , 80000,
#'     100   , FALSE  , NA        , NA         , NA
#'   )
#'   con <- wrp_connect()
#'   con %>%
#'     clear_script() %>%
#'     wrp_new_gts() %>%
#'     wrp_rename("test") %>%
#'     wrp_add_value_df(df) %>%
#'     wrp_exec()
#' }
#'
#' @export
#'
wrp_add_value_df <- function(wrp_con, df, tick = "tick", value = "value", latitude = NULL, longitude = NULL,
                             elevation = NULL) {
  tick      <- rlang::enquo(tick)
  value     <- rlang::enquo(value)
  latitude  <- rlang::enquo(latitude)
  longitude <- rlang::enquo(longitude)
  elevation <- rlang::enquo(elevation)
  vars      <- tidyselect::vars_select(names(df), tick = !!tick, value = !!value, latitude = !!latitude,
                                       longitude = !!longitude, elevation = !!elevation)
  df_script <- stats::setNames(df[, vars], names(vars))
  if (is.null(rlang::get_expr(latitude)))  df_script[, "latitude"]  <- NA
  if (is.null(rlang::get_expr(longitude))) df_script[, "longitude"] <- NA
  if (is.null(rlang::get_expr(elevation))) df_script[, "elevation"] <- NA
  purrr::pwalk(df_script, wrp_add_value, wrp_con = wrp_con)
  return(wrp_con)
}
#'
